/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.freshtax.myapp.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for InvGstr1.
 */
public class InvGstr1DTO {
    public Long id;
    public String gstin;
    public String state;
    public String flag;
    public String chksum;
    public String inum;
    public LocalDate idt;
    public String invRef;
    public String invTyp;
    public LocalDate invDue;
    public String rchrg;
    public String proAst;
    public String terms;
    public String orNo;
    public LocalDate orDt;
    public String etin;
    public String ctin;
    public String pos;
    public String cusNotes;
    public String tnc;
    public BigDecimal val;
    public String supType;
    public String ftInvProcessed;
    public String ftInvEdit;
    
  //added by ajay
    public List<InvItemGstr1DTO> invoiceItems;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}