/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.freshtax.myapp.dto;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for InvItemGstr1.
 */
public class InvItemGstr1DTO {
    public Long iniSno;
    public String itemDesc;
    public String itemTyp;
    public String hsn;
    public BigInteger qty;
    public String uom;
    public BigDecimal rate;
    public BigDecimal disc;
    public BigDecimal itTxval;
    public BigDecimal itRt;
    public Double itCpct;
    public BigDecimal itCamt;
    public Double itSpct;
    public BigDecimal itSamt;
    public Double itIpct;
    public BigDecimal itIamt;
    public Double itCspct;
    public BigDecimal itCsamt;
    public BigDecimal itTotal;
    public Long id;
    public InvGstr1DTO invoice;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}