/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.freshtax.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.freshtax.myapp.dto.InvGstr1DTO;
import com.freshtax.myapp.dto.InvGstr1DTOService;
import com.freshtax.myapp.dto.support.PageRequestByExample;
import com.freshtax.myapp.dto.support.PageResponse;
import com.freshtax.myapp.repository.InvGstr1Repository;
import com.freshtax.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/invoices")
public class InvGstr1Resource {

    private final Logger log = LoggerFactory.getLogger(InvGstr1Resource.class);

    @Inject
    private InvGstr1Repository invGstr1Repository;
    @Inject
    private InvGstr1DTOService invGstr1DTOService;

    /**
     * Create a new InvGstr1.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<InvGstr1DTO> create(@RequestBody InvGstr1DTO invGstr1DTO) throws URISyntaxException {

        log.debug("Create InvGstr1DTO : {}", invGstr1DTO);

        if (!invGstr1DTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create InvGstr1 without Invoice ID").body(null);
        }

        InvGstr1DTO result = invGstr1DTOService.save(invGstr1DTO);

        return ResponseEntity.created(new URI("/api/invoices/" + result.id)).body(result);
    }
    
    /**
     * Find All GSTR1 invoices.
     */
    @RequestMapping(value = "/", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<InvGstr1DTO>> getAll() throws URISyntaxException {

        log.debug("Find InvGstr1DTO : {}");

        List<InvGstr1DTO> result = invGstr1DTOService.getAll();

        return ResponseEntity.ok().body(result);
    }
    
    /**
    * Find by id InvGstr1.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<InvGstr1DTO> findById(@PathVariable Long id) throws URISyntaxException {

        log.debug("Find by id InvGstr1 : {}", id);

        return Optional.ofNullable(invGstr1DTOService.findOne(id)).map(invGstr1DTO -> new ResponseEntity<>(invGstr1DTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update InvGstr1.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<InvGstr1DTO> update(@RequestBody InvGstr1DTO invGstr1DTO) throws URISyntaxException {

        log.debug("Update InvGstr1DTO : {}", invGstr1DTO);

        if (!invGstr1DTO.isIdSet()) {
            return create(invGstr1DTO);
        }

        InvGstr1DTO result = invGstr1DTOService.save(invGstr1DTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of InvGstr1 using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<InvGstr1DTO>> findAll(@RequestBody PageRequestByExample<InvGstr1DTO> prbe) throws URISyntaxException {
        PageResponse<InvGstr1DTO> pageResponse = invGstr1DTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<InvGstr1DTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<InvGstr1DTO> results = invGstr1DTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id InvGstr1.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Long id) throws URISyntaxException {

        log.debug("Delete by id InvGstr1 : {}", id);

        try {
            invGstr1Repository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}