//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {InvGstr1} from './invGstr1';
import {InvGstr1Service} from './invGstr1.service';

@Component({
    moduleId: module.id,
	templateUrl: 'invGstr1-detail.component.html',
	selector: 'invGstr1-detail',
})
export class InvGstr1DetailComponent implements OnInit, OnDestroy {
    invGstr1 : InvGstr1;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<InvGstr1>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private invGstr1Service: InvGstr1Service) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for invGstr1-detail ' + id);

            if (id === 'new') {
                this.invGstr1 = new InvGstr1();
            } else {
                this.invGstr1Service.getInvGstr1(id)
                    .subscribe(invGstr1 => {
                            this.invGstr1 = invGstr1;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.invGstr1Service.update(this.invGstr1).
            subscribe(
                invGstr1 => {
                    this.invGstr1 = invGstr1;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.invGstr1);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
