//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-line.component.ts.e.vm
//
import {Component, Input} from '@angular/core';
import {InvTaxItemGstr1} from './invTaxItemGstr1';

@Component({
	template: `
        {{ invTaxItemGstr1?.num }} {{ invTaxItemGstr1?.rt }} {{ invTaxItemGstr1?.txval }} 	`,
	selector: 'invTaxItemGstr1-line',
})
export class InvTaxItemGstr1LineComponent {
    @Input() invTaxItemGstr1 : InvTaxItemGstr1;
}
