//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {InvGstr1} from '../invGstr1/invGstr1';

export class InvTaxItemGstr1 {
    // Raw attributes
    id : number;
    num : number;
    rt;
    txval;
    iamt;
    itIpct;
    camt;
    itCpct;
    samt;
    itSpct;
    csamt;
    itCspct;
    rt1 : number;
    txval1 : number;
    iamt1 : number;
    itIpct1 : number;
    camt1 : number;
    itCpct1 : number;
    samt1 : number;
    itSpct1 : number;
    csamt1 : number;
    itCspct1 : number;
    // x-to-one
    inv : InvGstr1;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.num = json.num;
            this.rt = json.rt;
            this.txval = json.txval;
            this.iamt = json.iamt;
            this.itIpct = json.itIpct;
            this.camt = json.camt;
            this.itCpct = json.itCpct;
            this.samt = json.samt;
            this.itSpct = json.itSpct;
            this.csamt = json.csamt;
            this.itCspct = json.itCspct;
            this.rt1 = json.rt1;
            this.txval1 = json.txval1;
            this.iamt1 = json.iamt1;
            this.itIpct1 = json.itIpct1;
            this.camt1 = json.camt1;
            this.itCpct1 = json.itCpct1;
            this.samt1 = json.samt1;
            this.itSpct1 = json.itSpct1;
            this.csamt1 = json.csamt1;
            this.itCspct1 = json.itCspct1;

            if (json.inv != null) {
                this.inv = new InvGstr1(json.inv);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : InvTaxItemGstr1[] {
        let invTaxItemGstr1s : InvTaxItemGstr1[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                invTaxItemGstr1s.push(new InvTaxItemGstr1(json));
            }
        }
        return invTaxItemGstr1s;
    }
}
