/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.freshtax.myapp.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Logger;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import com.freshtax.myapp.validation.FixedLength;
import com.google.common.base.MoreObjects;

@Entity
@Table(name = "devfreshtax.inv_gstr_1")
public class InvGstr1 implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(InvGstr1.class.getName());

    // Raw attributes
    private Long id;
    private String gstin;
    private String state;
    private String flag;
    private String chksum;
    private String inum;
    private LocalDate idt;
    private String invRef;
    private String invTyp;
    private LocalDate invDue;
    private String rchrg;
    private String proAst;
    private String terms;
    private String orNo;
    private LocalDate orDt;
    private String etin;
    private String ctin;
    private String pos;
    private String cusNotes;
    private String tnc;
    private BigDecimal val;
    private String supType;
    private String ftInvProcessed;
    private String ftInvEdit;
    
    private List<InvItemGstr1> invoiceItems;

    /*@PrePersist
    protected void prePersist()
    {
    	val = val.setScale(2, RoundingMode.HALF_EVEN);
    }*/
    
    
    @Override
    public String entityClassName() {
        return InvGstr1.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "inv_id", precision = 19)
    @Id
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public InvGstr1 id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [gstin] ------------------------

    @Size(max = 15)
    @Column(name = "gstin", length = 15)
    public String getGstin() {
        return gstin;
    }

    public void setGstin(String gstin) {
        this.gstin = gstin;
    }

    public InvGstr1 gstin(String gstin) {
        setGstin(gstin);
        return this;
    }
    // -- [state] ------------------------

    @Size(max = 2)
    @Column(name = "\"state\"", length = 2)
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public InvGstr1 state(String state) {
        setState(state);
        return this;
    }
    // -- [flag] ------------------------

    @FixedLength(length = 1)
    @Column(name = "flag", length = 1)
    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public InvGstr1 flag(String flag) {
        setFlag(flag);
        return this;
    }
    // -- [chksum] ------------------------

    @Size(max = 64)
    @Column(name = "chksum", length = 64)
    public String getChksum() {
        return chksum;
    }

    public void setChksum(String chksum) {
        this.chksum = chksum;
    }

    public InvGstr1 chksum(String chksum) {
        setChksum(chksum);
        return this;
    }
    // -- [inum] ------------------------

    @Size(max = 16)
    @Column(name = "inum", length = 16)
    public String getInum() {
        return inum;
    }

    public void setInum(String inum) {
        this.inum = inum;
    }

    public InvGstr1 inum(String inum) {
        setInum(inum);
        return this;
    }
    // -- [idt] ------------------------

    @Column(name = "idt", length = 13)
    public LocalDate getIdt() {
        return idt;
    }

    public void setIdt(LocalDate idt) {
        this.idt = idt;
    }

    public InvGstr1 idt(LocalDate idt) {
        setIdt(idt);
        return this;
    }
    // -- [invRef] ------------------------

    @Size(max = 100)
    @Column(name = "inv_ref", length = 100)
    public String getInvRef() {
        return invRef;
    }

    public void setInvRef(String invRef) {
        this.invRef = invRef;
    }

    public InvGstr1 invRef(String invRef) {
        setInvRef(invRef);
        return this;
    }
    // -- [invTyp] ------------------------

    @Size(max = 5)
    @Column(name = "inv_typ", length = 5)
    public String getInvTyp() {
        return invTyp;
    }

    public void setInvTyp(String invTyp) {
        this.invTyp = invTyp;
    }

    public InvGstr1 invTyp(String invTyp) {
        setInvTyp(invTyp);
        return this;
    }
    // -- [invDue] ------------------------

    @Column(name = "inv_due", length = 13)
    public LocalDate getInvDue() {
        return invDue;
    }

    public void setInvDue(LocalDate invDue) {
        this.invDue = invDue;
    }

    public InvGstr1 invDue(LocalDate invDue) {
        setInvDue(invDue);
        return this;
    }
    // -- [rchrg] ------------------------

    @FixedLength(length = 1)
    @Column(name = "rchrg", length = 1)
    public String getRchrg() {
        return rchrg;
    }

    public void setRchrg(String rchrg) {
        this.rchrg = rchrg;
    }

    public InvGstr1 rchrg(String rchrg) {
        setRchrg(rchrg);
        return this;
    }
    // -- [proAst] ------------------------

    @FixedLength(length = 1)
    @Column(name = "pro_ast", length = 1)
    public String getProAst() {
        return proAst;
    }

    public void setProAst(String proAst) {
        this.proAst = proAst;
    }

    public InvGstr1 proAst(String proAst) {
        setProAst(proAst);
        return this;
    }
    // -- [terms] ------------------------

    @Size(max = 2147483647)
    @Column(name = "terms", length = 2147483647)
    public String getTerms() {
        return terms;
    }

    public void setTerms(String terms) {
        this.terms = terms;
    }

    public InvGstr1 terms(String terms) {
        setTerms(terms);
        return this;
    }
    // -- [orNo] ------------------------

    @Size(max = 2147483647)
    @Column(name = "or_no", length = 2147483647)
    public String getOrNo() {
        return orNo;
    }

    public void setOrNo(String orNo) {
        this.orNo = orNo;
    }

    public InvGstr1 orNo(String orNo) {
        setOrNo(orNo);
        return this;
    }
    // -- [orDt] ------------------------

    @Column(name = "or_dt", length = 13)
    public LocalDate getOrDt() {
        return orDt;
    }

    public void setOrDt(LocalDate orDt) {
        this.orDt = orDt;
    }

    public InvGstr1 orDt(LocalDate orDt) {
        setOrDt(orDt);
        return this;
    }
    // -- [etin] ------------------------

    @Size(max = 15)
    @Column(name = "etin", length = 15)
    public String getEtin() {
        return etin;
    }

    public void setEtin(String etin) {
        this.etin = etin;
    }

    public InvGstr1 etin(String etin) {
        setEtin(etin);
        return this;
    }
    // -- [ctin] ------------------------

    @Size(max = 15)
    @Column(name = "ctin", length = 15)
    public String getCtin() {
        return ctin;
    }

    public void setCtin(String ctin) {
        this.ctin = ctin;
    }

    public InvGstr1 ctin(String ctin) {
        setCtin(ctin);
        return this;
    }
    // -- [pos] ------------------------

    @Size(max = 2)
    @Column(name = "pos", length = 2)
    public String getPos() {
        return pos;
    }

    public void setPos(String pos) {
        this.pos = pos;
    }

    public InvGstr1 pos(String pos) {
        setPos(pos);
        return this;
    }
    // -- [cusNotes] ------------------------

    @Size(max = 2147483647)
    @Column(name = "cus_notes", length = 2147483647)
    public String getCusNotes() {
        return cusNotes;
    }

    public void setCusNotes(String cusNotes) {
        this.cusNotes = cusNotes;
    }

    public InvGstr1 cusNotes(String cusNotes) {
        setCusNotes(cusNotes);
        return this;
    }
    // -- [tnc] ------------------------

    @Size(max = 2147483647)
    @Column(name = "tnc", length = 2147483647)
    public String getTnc() {
        return tnc;
    }

    public void setTnc(String tnc) {
        this.tnc = tnc;
    }

    public InvGstr1 tnc(String tnc) {
        setTnc(tnc);
        return this;
    }
    // -- [val] ------------------------

    @Digits(integer = 10, fraction = 2)
    @Column(name = "val", precision = 10, scale = 2 )
    public BigDecimal getVal() {
        return val;
    }

    public void setVal(BigDecimal val) {
        this.val = val;
    }

    public InvGstr1 val(BigDecimal val) {
        setVal(val);
        return this;
    }
    // -- [supType] ------------------------

    @Size(max = 10)
    @Column(name = "sup_type", length = 10)
    public String getSupType() {
        return supType;
    }

    public void setSupType(String supType) {
        this.supType = supType;
    }

    public InvGstr1 supType(String supType) {
        setSupType(supType);
        return this;
    }
    // -- [ftInvProcessed] ------------------------

    @Size(max = 1)
    @Column(name = "ft_inv_processed", length = 1)
    public String getFtInvProcessed() {
        return ftInvProcessed;
    }

    public void setFtInvProcessed(String ftInvProcessed) {
        this.ftInvProcessed = ftInvProcessed;
    }

    public InvGstr1 ftInvProcessed(String ftInvProcessed) {
        setFtInvProcessed(ftInvProcessed);
        return this;
    }
    // -- [ftInvEdit] ------------------------

    @Size(max = 1)
    @Column(name = "ft_inv_edit", length = 1)
    public String getFtInvEdit() {
        return ftInvEdit;
    }

    public void setFtInvEdit(String ftInvEdit) {
        this.ftInvEdit = ftInvEdit;
    }

    public InvGstr1 ftInvEdit(String ftInvEdit) {
        setFtInvEdit(ftInvEdit);
        return this;
    }
    
    // -- [invoice Items] ------------------------
    @JoinColumn(name="inv_id",referencedColumnName="inv_id")
    @OneToMany(cascade=CascadeType.ALL,targetEntity=InvItemGstr1.class,fetch=FetchType.EAGER)
    public List<InvItemGstr1> getInvoiceItems() {
		return invoiceItems;
	}

	public void setInvoiceItems(List<InvItemGstr1> invoiceItems) {
		this.invoiceItems = invoiceItems;
	}
	
	public InvGstr1 invoiceItems(List<InvItemGstr1> invoiceItems) {
		setInvoiceItems(invoiceItems);
        return this;
    }
	
    /**
     * Apply the default values.
     */
    public InvGstr1 withDefaults() {
        return this;
    }

    
	/**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof InvGstr1 && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this InvGstr1 instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("gstin", getGstin()) //
                .add("state", getState()) //
                .add("flag", getFlag()) //
                .add("chksum", getChksum()) //
                .add("inum", getInum()) //
                .add("idt", getIdt()) //
                .add("invRef", getInvRef()) //
                .add("invTyp", getInvTyp()) //
                .add("invDue", getInvDue()) //
                .add("rchrg", getRchrg()) //
                .add("proAst", getProAst()) //
                .add("terms", getTerms()) //
                .add("orNo", getOrNo()) //
                .add("orDt", getOrDt()) //
                .add("etin", getEtin()) //
                .add("ctin", getCtin()) //
                .add("pos", getPos()) //
                .add("cusNotes", getCusNotes()) //
                .add("tnc", getTnc()) //
                .add("val", getVal()) //
                .add("supType", getSupType()) //
                .add("ftInvProcessed", getFtInvProcessed()) //
                .add("ftInvEdit", getFtInvEdit()) //
                .toString();
    }
}