/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.freshtax.myapp.domain;

import java.math.BigInteger;
import java.time.LocalDate;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(InvGstr1.class)
public abstract class InvGstr1_ {

    // Raw attributes
    public static volatile SingularAttribute<InvGstr1, Long> id;
    public static volatile SingularAttribute<InvGstr1, String> gstin;
    public static volatile SingularAttribute<InvGstr1, String> state;
    public static volatile SingularAttribute<InvGstr1, String> flag;
    public static volatile SingularAttribute<InvGstr1, String> chksum;
    public static volatile SingularAttribute<InvGstr1, String> inum;
    public static volatile SingularAttribute<InvGstr1, LocalDate> idt;
    public static volatile SingularAttribute<InvGstr1, String> invRef;
    public static volatile SingularAttribute<InvGstr1, String> invTyp;
    public static volatile SingularAttribute<InvGstr1, LocalDate> invDue;
    public static volatile SingularAttribute<InvGstr1, String> rchrg;
    public static volatile SingularAttribute<InvGstr1, String> proAst;
    public static volatile SingularAttribute<InvGstr1, String> terms;
    public static volatile SingularAttribute<InvGstr1, String> orNo;
    public static volatile SingularAttribute<InvGstr1, LocalDate> orDt;
    public static volatile SingularAttribute<InvGstr1, String> etin;
    public static volatile SingularAttribute<InvGstr1, String> ctin;
    public static volatile SingularAttribute<InvGstr1, String> pos;
    public static volatile SingularAttribute<InvGstr1, String> cusNotes;
    public static volatile SingularAttribute<InvGstr1, String> tnc;
    public static volatile SingularAttribute<InvGstr1, BigInteger> val;
    public static volatile SingularAttribute<InvGstr1, String> supType;
    public static volatile SingularAttribute<InvGstr1, String> ftInvProcessed;
    public static volatile SingularAttribute<InvGstr1, String> ftInvEdit;
}