/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.freshtax.myapp.domain;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(InvItemGstr1.class)
public abstract class InvItemGstr1_ {

    // Raw attributes
    public static volatile SingularAttribute<InvItemGstr1, Long> iniSno;
    public static volatile SingularAttribute<InvItemGstr1, String> itemDesc;
    public static volatile SingularAttribute<InvItemGstr1, String> itemTyp;
    public static volatile SingularAttribute<InvItemGstr1, String> hsn;
    public static volatile SingularAttribute<InvItemGstr1, BigInteger> qty;
    public static volatile SingularAttribute<InvItemGstr1, String> uom;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> rate;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> disc;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> itTxval;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> itRt;
    public static volatile SingularAttribute<InvItemGstr1, Double> itCpct;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> itCamt;
    public static volatile SingularAttribute<InvItemGstr1, Double> itSpct;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> itSamt;
    public static volatile SingularAttribute<InvItemGstr1, Double> itIpct;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> itIamt;
    public static volatile SingularAttribute<InvItemGstr1, Double> itCspct;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> itCsamt;
    public static volatile SingularAttribute<InvItemGstr1, BigDecimal> itTotal;
    public static volatile SingularAttribute<InvItemGstr1, Long> id;

    // Many to one
    public static volatile SingularAttribute<InvItemGstr1, InvGstr1> inv;
}