/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.freshtax.myapp.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.freshtax.myapp.domain.InvGstr1;
import com.freshtax.myapp.domain.InvGstr1_;

public interface InvGstr1Repository extends JpaRepository<InvGstr1, Long> {

    default List<InvGstr1> complete(String query, int maxResults) {
        InvGstr1 probe = new InvGstr1();
        probe.setGstin(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(InvGstr1_.gstin.getName(), match -> match.ignoreCase().startsWith());

        Page<InvGstr1> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
    
    List<InvGstr1> findAll();
}