//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/app.routes.ts.p.vm
//
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home.component';

import { InvGstr1ListComponent } from './entities/invGstr1/invGstr1-list.component';
import { InvGstr1DetailComponent } from './entities/invGstr1/invGstr1-detail.component';

import { InvItemGstr1ListComponent } from './entities/invItemGstr1/invItemGstr1-list.component';
import { InvItemGstr1DetailComponent } from './entities/invItemGstr1/invItemGstr1-detail.component';

import { UserListComponent } from './entities/user/user-list.component';
import { UserDetailComponent } from './entities/user/user-detail.component';

export const routes: Routes = [
    { path : '',  component: HomeComponent }
    ,
    {path: 'invGstr1-list', component: InvGstr1ListComponent },
    {path: 'invGstr1/:id', component: InvGstr1DetailComponent }
    ,
    {path: 'invItemGstr1-list', component: InvItemGstr1ListComponent },
    {path: 'invItemGstr1/:id', component: InvItemGstr1DetailComponent }
    ,
    {path: 'user-list', component: UserListComponent },
    {path: 'user/:id', component: UserDetailComponent }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
