//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { InvItemGstr1 } from './invItemGstr1';

@Injectable()
export class InvItemGstr1Service {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a InvItemGstr1 by id.
     */
    getInvItemGstr1(id : any) : Observable<InvItemGstr1> {
        return this.http.get('/api/invItemGstr1s/' + id)
            .map(response => new InvItemGstr1(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed invItemGstr1.
     */
    update(invItemGstr1 : InvItemGstr1) : Observable<InvItemGstr1> {
        let body = JSON.stringify(invItemGstr1);

        return this.http.put('/api/invItemGstr1s/', body, this.options)
            .map(response => new InvItemGstr1(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of InvItemGstr1 using the passed
     * invItemGstr1 as an example for the search by example facility.
     */
    getPage(invItemGstr1 : InvItemGstr1, event : LazyLoadEvent) : Observable<PageResponse<InvItemGstr1>> {
        let req = new PageRequestByExample(invItemGstr1, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/invItemGstr1s/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<InvItemGstr1>(pr.totalPages, pr.totalElements, InvItemGstr1.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by InvItemGstr1CompleteComponent.
     */
    complete(query : string) : Observable<InvItemGstr1[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/invItemGstr1s/complete', body, this.options)
            .map(response => InvItemGstr1.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an InvItemGstr1 by id.
     */
    delete(id : any) {
        return this.http.delete('/api/invItemGstr1s/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
